sudo: required
language: node_js
node_js:
  - "9.11.3"
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm install -g truffle
  - npm install -g ganache-cli
script:
  - npm run ganache
  - sleep 5
  - truffle migrate
  - truffle test
  - npm run stop